project_id = "iqeubhhqdurqoaxnnyng"

[functions.delete-all-users-except]
verify_jwt = true

[functions.import-wallet]
verify_jwt = true

[functions.check-login]
verify_jwt = false

[functions.track-visitor]
verify_jwt = false

[functions.generate-admin-fee-addresses]
verify_jwt = true

[functions.release-escrow]
verify_jwt = true

[functions.auto-release-escrow]
verify_jwt = false

[functions.withdraw-admin-fees]
verify_jwt = true