project_id = "iqeubhhqdurqoaxnnyng"

[functions.delete-all-users-except]
verify_jwt = true

[functions.import-wallet]
verify_jwt = true

[functions.check-login]
verify_jwt = false

[functions.track-visitor]
verify_jwt = false

[functions.generate-admin-fee-addresses]
verify_jwt = true

[functions.release-escrow]
verify_jwt = true

[functions.auto-release-escrow]
verify_jwt = false

[functions.withdraw-admin-fees]
verify_jwt = true

[functions.resolve-dispute]
verify_jwt = false

[functions.fix-deposit-balance]
verify_jwt = false

[functions.manual-balance-correction]
verify_jwt = false

[functions.manual-ltc-transfer]
verify_jwt = false

[functions.check-central-deposits]
verify_jwt = false

[functions.generate-tatum-pool-addresses]
verify_jwt = true

[functions.process-tatum-withdrawal]
verify_jwt = true

[functions.generate-deposit-address]
verify_jwt = false

[functions.monitor-deposits]
verify_jwt = false
